infohudVersion: '1.3'
messageUpdateDelay: 5
biomeUpdateDelay: 40
brightBiomes:
- DESERT
- DESERT_HILLS
- ICE_DESERT
- BEACH
- SNOWY_BEACH
- COLD_BEACH
- SNOWY_TUNDRA
- COLD_TUNDRA
- ICE_FLATS
- MUTATED_ICE_FLATS
- SNOWY_TAIGA
- SNOWY_TAIGA_HILLS
- SNOWY_TAIGA_MOUNTAINS
- COLD_TAIGA
- COLD_TAIGA_HILLS
- COLD_TAIGA_MOUNTAINS
- ICE_MOUNTAINS
- SNOWY_MOUNTAINS
- COLD_MOUNTAINS
- EXTREME_HILLS
- EXTREME_HILLS_PLUS_MOUNTAINS
- GRAVELLY_MOUNTAINS
- MODIFIED_GRAVELLY_MOUNTAINS
- ICE_PLAINS
- ICE_PLAINS_SPIKE
- ICE_SPIKES
- FROZEN_RIVER
playerConfig: {}