#Bright Biomes:
#    Find the list of biomes at https://minecraft.gamepedia.com/Biome#Biome_IDs.
#    Alternatively enter the biome as it appears in the F3 menu, or use /infohud biome add
#    Must be in UPPERCASE. Eg. DEEP_FROZEN_OCEAN
#
#Refresh Rate:
#    Number of ticks between each update
#
#Player Configuration Structure
# playerConfig:
#   UUID:
#     coordinatesMode: <0:Enabled | 1:Disabled>
#     timeMode: <0:Disabled | 1:Current Tick | 2:24h Clock | 3: 1.14 Villager Schedule>
#     darkMode: <0:Disabled | 1:Enabled>

refreshRate: 5
brightBiomes:
- DESERT
- DESERT_HILLS
- ICE_DESERT
- BEACH
- SNOWY_BEACH
- COLD_BEACH
- SNOWY_TUNDRA
- COLD_TUNDRA
- ICE_FLATS
- MUTATED_ICE_FLATS
- SNOWY_TAIGA
- SNOWY_TAIGA_HILLS
- SNOWY_TAIGA_MOUNTAINS
- COLD_TAIGA
- COLD_TAIGA_HILLS
- COLD_TAIGA_MOUNTAINS
- ICE_MOUNTAINS
- SNOWY_MOUNTAINS
- COLD_MOUNTAINS
- EXTREME_HILLS
- EXTREME_HILLS_PLUS_MOUNTAINS
- GRAVELLY_MOUNTAINS
- MODIFIED_GRAVELLY_MOUNTAINS
- ICE_PLAINS
- ICE_PLAINS_SPIKE
- ICE_SPIKES
- FROZEN_RIVER
playerConfig: {}