refreshRate: 5
brightBiomes:
- DESERT
- SAVANNA
- SNOWY_TUNDRA
- SNOWY_MOUNTAINS
- SNOWY_BEACH
- SNOWY_TAIGA
- SNOWY_TAIGA_HILLS
- SNOWY_TAIGA_MOUNTAINS
- ICE_SPIKES
- MOUNTAINS
- GRAVELLY_MOUNTAINS
- MODIFIED_GRAVELLY_MOUNTAINS
- BEACH
- SNOWY_BEACH
playerConfig: []